### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by coonsd** [sprinteins/ghost#14]
There doesn't appear to be a license attached to the project yet.  If one has already been selected it should be added to the root folder as LICENSE.txt or similar.  There wasn't enough information on the goals of the project for me to suggest a specific license, but here are a couple good resources to help with the decision process:

[https://opensource.org/licenses](https://opensource.org/licenses)
[https://choosealicense.com/](https://choosealicense.com/)

Why is this important? Without a license the project has zero control over how the code is used, modified, named, in the future, and it may be difficult to assert those rights in the future if the project chooses to change.  Also, a license can be used to express that there are no warranties that come with the code, which could help guard against liability issues should someone use the code.  Even if the project doesn't plan to enforce any rules about the work, a lack of a license could make others wary to use it since it is unclear what the implications could be.

**Comment by N3ol4N** [comment]
Thanks a lot for your input,
we will take care of that immediately and add a LICENSE.txt for the project.
