### ISSUE TITLE
Sorting in reverse order

### ISSUE THREAD

**Issue by N3ol4N** [sprinteins/ghost#6]
In the current state, Ghost can sort the tablecolumns in descending alphabetical or numeralorders.
Suggestion: Sorting in ascending order

**Comment by liuxh0** [comment]
Do you mean sorting only in ascending order or switching between ascending and descending order?

**Comment by L4B0MB4** [comment]
Its about switching between desc and asc. By clicking the table-header-column (e.g. "number of changes") we want to order desc. If you click another time it should order asc.
